version: '3.8'

volumes:
  ipython_data:

services:

  postgres:
    build:
      context: .
      dockerfile: ./containers/postgres/Dockerfile
    volumes:
      - ./containers/data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./containers/.envs/.postgres

  redis:
    image: redis:7.2-rc-alpine

  api:
    image: night_manga_be
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: /bin/sh ./start-dev.sh
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.development
    env_file:
      - ./containers/.envs/.postgres
    volumes:
      - ./apps:/usr/src/apps
      - ipython_data:/root/.ipython
    links:
      - postgres
      - redis

  worker:
    image: night_manga_be
    command: "celery -A core worker -P eventlet -c 5"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.development
    env_file:
      - ./containers/.envs/.postgres
    volumes:
      - ./apps:/usr/src/apps
    links:
      - postgres
      - redis

  beat:
    image: night_manga_be
    command: "celery -A core beat"
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.development
    env_file:
      - ./containers/.envs/.postgres
    volumes:
      - ./apps:/usr/src/apps
    links:
      - postgres
      - redis
  nginx:
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./containers/nginx/conf.d:/etc/nginx/conf.d
      - ./containers/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./apps/static:/usr/src/api_staticfiles
      - ./apps/media:/usr/src/api_media
    links:
      - api
    ports:
      - 8000:80

