version: '3.8'

volumes:
  ipython_data:
  staticfiles:
  media:

services:
  redis:
    image: '7.2-rc-alpine'

  api:
    image: night_manga_be
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: /usr/src/apps/gunicorn.sh
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.development
      #- DATABASE_URL=postgresql://dbadmin:pA55w0rd!@development.clur3vk7dq2s.us-east-1.rds.amazonaws.com:5432/development
    env_file:
      - ./containers/.envs/.django
    volumes:
      - ./apps:/usr/src/apps
      - staticfiles:/usr/src/apps/staticfiles
      - media:/usr/src/apss/media
      - ipython_data:/root/.ipython
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: "celery -A app.core worker -P gevent -c 5"
    depends_on:
      - pgbouncer
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    env_file:
      - ./containers/.envs/.local/.django
    volumes:
      - ./api:/usr/src/api
      - api_staticfiles:/usr/src/api_staticfiles
      - api_media:/usr/src/api_media
    links:
      - pgbouncer
      - redis

  beat:
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    command: "celery -A app.core beat"
    depends_on:
      - pgbouncer
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    env_file:
      - ./containers/.envs/.local/.celery
    volumes:
      - ./apps:/usr/src/apps
      - staticfiles:/usr/src/apps/staticfiles
      - media:/usr/src/apps/media
    links:
      - pgbouncer
      - redis

  postgres:
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - ./containers/data/postgres:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./containers/.envs/.postgres
    ports:
      - 5432:5432